import {
  addDoc,
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  where,
  type Unsubscribe,
} from "firebase/firestore";
import { getFirebaseAuth, getFirebaseDb } from "./firebase";

export type UserProfile = { uid:string; name:string; email:string; phone?:string; nitraId:string; initials:string; bio?:string; status?:string; avatarUrl?:string; role?:string; location?:string; website?:string; privacy?:Record<string, boolean> };
export type Conversation = { id:string; type:"direct"|"group"; title?:string; participantIds:string[]; lastMessageId?:string; lastMessageText?:string; lastMessageAt?:unknown };
export type ChatMessage = { id:string; senderId:string; text:string; replyToId?:string; reactions?:Record<string,string[]>; editedAt?:unknown; deletedAt?:unknown; createdAt?:unknown };
export type FriendRequestStatus = "pending"|"accepted"|"declined"|"cancelled";
export type FriendRequest = { id:string; senderId:string; receiverId:string; status:FriendRequestStatus; createdAt?:unknown; updatedAt?:unknown };
function getUsersRef(){return collection(getFirebaseDb(),"users")}
function getConversationsRef(){return collection(getFirebaseDb(),"conversations")}
function getFriendRequestsRef(){return collection(getFirebaseDb(),"friendRequests")}
export async function getUserProfile(uid:string):Promise<UserProfile|null>{const s=await getDoc(doc(getFirebaseDb(),"users",uid));if(!s.exists())return null;return{uid:s.id,...(s.data() as Omit<UserProfile,"uid">)}}
export async function createUserProfile(profile:UserProfile){await setDoc(doc(getFirebaseDb(),"users",profile.uid),{name:profile.name,email:profile.email,phone:profile.phone||"",nitraId:profile.nitraId,initials:profile.initials,bio:profile.bio||"",status:profile.status||"Available",avatarUrl:profile.avatarUrl||"",role:profile.role||"",location:profile.location||"",website:profile.website||"",privacy:profile.privacy||{showEmail:false,showPhone:false},createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
export async function updateUserProfile(uid:string,patch:Partial<UserProfile>){const{uid:_uid,...safePatch}=patch;await updateDoc(doc(getFirebaseDb(),"users",uid),{...safePatch,updatedAt:serverTimestamp()})}
export async function searchUsers(search:string,currentUid?:string):Promise<UserProfile[]>{const normalized=search.trim().toLowerCase();if(!normalized)return[];const results=new Map<string,UserProfile>();for(const field of ["nitraId","email","name","phone"] as const){const s=await getDocs(query(getUsersRef(),where(field,">=",normalized),where(field,"<=",normalized+"\uf8ff"),limit(10)));s.forEach(i=>{if(i.id!==currentUid)results.set(i.id,{uid:i.id,...(i.data() as Omit<UserProfile,"uid">)})})}return[...results.values()].slice(0,20)}
export async function getFriendRequestBetween(uid:string,otherUid:string):Promise<FriendRequest|null>{const a=await getDocs(query(getFriendRequestsRef(),where("senderId","==",uid),where("receiverId","==",otherUid),limit(10)));const b=await getDocs(query(getFriendRequestsRef(),where("senderId","==",otherUid),where("receiverId","==",uid),limit(10)));return[...a.docs,...b.docs].map(i=>({id:i.id,...(i.data() as Omit<FriendRequest,"id">)})).find(x=>x.status==="pending"||x.status==="accepted")||null}
export async function sendFriendRequest(senderId:string,receiverId:string){const authUser=getFirebaseAuth().currentUser;if(!authUser)throw Object.assign(new Error("You are not signed in to Firebase."),{code:"auth/not-signed-in"});if(authUser.uid!==senderId)throw Object.assign(new Error("Your Nitra session is out of sync. Please sign in again."),{code:"auth/session-mismatch"});if(senderId===receiverId)throw new Error("You cannot add yourself.");const existing=await getFriendRequestBetween(senderId,receiverId);if(existing?.status==="accepted"||existing?.status==="pending")return existing.id;return(await addDoc(getFriendRequestsRef(),{senderId,receiverId,status:"pending",createdAt:serverTimestamp(),updatedAt:serverTimestamp()})).id}
export async function updateFriendRequest(requestId:string,status:"accepted"|"declined"|"cancelled"){await updateDoc(doc(getFirebaseDb(),"friendRequests",requestId),{status,updatedAt:serverTimestamp()})}
export function subscribeToFriendRequests(uid:string,callback:(items:FriendRequest[])=>void):Unsubscribe{const r=getFriendRequestsRef();let a:FriendRequest[]=[];let b:FriendRequest[]=[];const emit=()=>callback([...a,...b]);const ua=onSnapshot(query(r,where("receiverId","==",uid),where("status","==","pending")),s=>{a=s.docs.map(i=>({id:i.id,...(i.data() as Omit<FriendRequest,"id">)}));emit()});const ub=onSnapshot(query(r,where("senderId","==",uid),where("status","==","pending")),s=>{b=s.docs.map(i=>({id:i.id,...(i.data() as Omit<FriendRequest,"id">)}));emit()});return()=>{ua();ub()}}
export function subscribeToFriends(uid:string,callback:(userIds:string[])=>void):Unsubscribe{const r=getFriendRequestsRef();let a:FriendRequest[]=[];let b:FriendRequest[]=[];const emit=()=>{const ids=new Set<string>();a.filter(x=>x.status==="accepted").forEach(x=>ids.add(x.senderId));b.filter(x=>x.status==="accepted").forEach(x=>ids.add(x.receiverId));callback([...ids])};const ua=onSnapshot(query(r,where("receiverId","==",uid)),s=>{a=s.docs.map(i=>({id:i.id,...(i.data() as Omit<FriendRequest,"id">)}));emit()});const ub=onSnapshot(query(r,where("senderId","==",uid)),s=>{b=s.docs.map(i=>({id:i.id,...(i.data() as Omit<FriendRequest,"id">)}));emit()});return()=>{ua();ub()}}
export async function findOrCreateDirectConversation(uid:string,otherUid:string){const existing=await getDocs(query(getConversationsRef(),where("participantIds","array-contains",uid),limit(50)));const match=existing.docs.find(i=>{const d=i.data();const p=(d.participantIds||[]) as string[];return d.type==="direct"&&p.length===2&&p.includes(otherUid)});if(match)return match.id;return(await addDoc(getConversationsRef(),{type:"direct",participantIds:[uid,otherUid],lastMessageText:"",createdAt:serverTimestamp(),updatedAt:serverTimestamp()})).id}
export function subscribeToConversations(uid:string,callback:(items:Conversation[])=>void):Unsubscribe{return onSnapshot(query(getConversationsRef(),where("participantIds","array-contains",uid),orderBy("updatedAt","desc")),s=>callback(s.docs.map(i=>({id:i.id,...(i.data() as Omit<Conversation,"id">)}))))}
export function subscribeToMessages(conversationId:string,callback:(items:ChatMessage[])=>void):Unsubscribe{return onSnapshot(query(collection(getFirebaseDb(),"conversations",conversationId,"messages"),orderBy("createdAt","asc")),s=>callback(s.docs.map(i=>({id:i.id,...(i.data() as Omit<ChatMessage,"id">)}))))}
export async function sendMessage(conversationId:string,senderId:string,text:string,replyToId?:string){const authUser=getFirebaseAuth().currentUser;if(!authUser||authUser.uid!==senderId)throw new Error("Your Firebase session is not ready. Please sign in again.");const cleanText=text.trim();if(!cleanText)return null;const created=await addDoc(collection(getFirebaseDb(),"conversations",conversationId,"messages"),{senderId,text:cleanText,replyToId:replyToId||null,reactions:{},createdAt:serverTimestamp()});await updateDoc(doc(getFirebaseDb(),"conversations",conversationId),{lastMessageId:created.id,lastMessageText:cleanText,lastMessageAt:serverTimestamp(),updatedAt:serverTimestamp()});return created.id}
export function mapFirestoreError(error:unknown){const code=(error as {code?:string})?.code||"";const map:Record<string,string>={"permission-denied":"Firestore denied this action. Publish the Firestore rules for this project.","failed-precondition":"Firestore needs an index for this query. Check the Firebase console.","auth/not-signed-in":"Your Firebase session is missing. Sign out and sign in again, then try again.","auth/session-mismatch":"Your Nitra session is out of sync with Firebase. Sign out and sign in again, then try again."};return map[code]||((error as {message?:string})?.message||"Something went wrong with Firebase.")}
