from pathlib import Path

p = Path('src/app/page.tsx')
s = p.read_text()
s = s.replace('import { mapFirestoreError } from "@/lib/firebase-chat";', 'import { findOrCreateDirectConversation, getUserProfile, mapFirestoreError, sendMessage as sendFirebaseMessage, subscribeToConversations, subscribeToMessages } from "@/lib/firebase-chat";')
s = s.replace('type Chat = { id: string; contact: Contact; messages: Message[]; pinned?: boolean; muted?: boolean; archived?: boolean; unread: number; lastTime: string };', 'type Chat = { id: string; contact: Contact; messages: Message[]; pinned?: boolean; muted?: boolean; archived?: boolean; unread: number; lastTime: string; firebaseConversationId?: string };')
needle = '  useEffect(() => { if (ready) localStorage.setItem(CHAT_STORAGE_KEY, JSON.stringify(chats)); }, [chats, ready]);\n'
insert = '''  useEffect(() => {\n    if (!ready || !user?.uid) return;\n    const unsubscribe = subscribeToConversations(user.uid, async (conversations) => {\n      const results = await Promise.all(conversations.map(async (conversation) => {\n        const otherUid = conversation.participantIds.find((id) => id !== user.uid);\n        if (!otherUid) return null;\n        const contact = await getUserProfile(otherUid);\n        if (!contact) return null;\n        return { conversation, contact };\n      }));\n      const valid = results.filter((item): item is NonNullable<typeof item> => Boolean(item));\n      setChats((prev) => {\n        const next = [...prev];\n        for (const item of valid) {\n          const id = `chat-${item.contact.uid}`;\n          const existing = next.findIndex((chat) => chat.id === id);\n          const contact: Contact = { id: item.contact.uid, name: item.contact.name, initials: item.contact.initials, email: item.contact.email, nitraId: item.contact.nitraId, bio: item.contact.bio, status: item.contact.status, online: true };\n          const chat = { id, contact, firebaseConversationId: item.conversation.id };\n          if (existing >= 0) next[existing] = { ...next[existing], ...chat };\n          else next.push({ ...chat, messages: [], unread: 0, lastTime: "New" });\n        }\n        return next;\n      });\n    });\n    return unsubscribe;\n  }, [ready, user?.uid]);\n\n  useEffect(() => {\n    if (!ready || !user?.uid) return;\n    const cleanups: (() => void)[] = [];\n    chats.filter((chat) => chat.firebaseConversationId).forEach((chat) => {\n      const conversationId = chat.firebaseConversationId!;\n      cleanups.push(subscribeToMessages(conversationId, (firebaseMessages) => {\n        setChats((prev) => prev.map((current) => {\n          if (current.firebaseConversationId !== conversationId) return current;\n          const messages: Message[] = firebaseMessages.map((m) => ({\n            id: hashMessageId(m.id),\n            from: m.senderId === user.uid ? "me" : "them",\n            text: m.text,\n            time: formatFirebaseTime(m.createdAt),\n          }));\n          const last = messages.at(-1);\n          return { ...current, messages, lastTime: last?.time || current.lastTime, unread: activeId === current.id ? 0 : messages.filter((m) => m.from === "them").length };\n        }));\n      }));\n    });\n    return () => cleanups.forEach((cleanup) => cleanup());\n  }, [ready, user?.uid, chats.map((chat) => chat.firebaseConversationId).join(","), activeId]);\n\n'''
s = s.replace(needle, needle + insert)
helper = '''function hashMessageId(value: string) {\n  let hash = 0;\n  for (let i = 0; i < value.length; i += 1) hash = ((hash << 5) - hash + value.charCodeAt(i)) | 0;\n  return Math.abs(hash);\n}\n\nfunction formatFirebaseTime(value: unknown) {\n  try {\n    const date = value && typeof value === "object" && "toDate" in value && typeof (value as { toDate?: () => Date }).toDate === "function" ? (value as { toDate: () => Date }).toDate() : new Date();\n    return date.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });\n  } catch { return "Now"; }\n}\n\n'''
s = s.replace('function Home() {', helper + 'function Home() {')
old = '''  const send = (override?: string) => {\n    const text = (override ?? message).trim();\n    if (!text || !active) return;\n    const now = new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });\n    setChats(p => p.map(c => c.id === active.id ? { ...c, lastTime: now, messages: [...c.messages, { id: Date.now(), from: "me", text, time: now }] } : c));\n    setMessage("");\n    setPicker(false);\n    inputRef.current?.focus();\n  };'''
new = '''  const send = async (override?: string) => {\n    const text = (override ?? message).trim();\n    if (!text || !active || !user?.uid) return;\n    try {\n      let conversationId = active.firebaseConversationId;\n      if (!conversationId) {\n        conversationId = await findOrCreateDirectConversation(user.uid, active.contact.id);\n        setChats((p) => p.map((c) => c.id === active.id ? { ...c, firebaseConversationId: conversationId } : c));\n      }\n      await sendFirebaseMessage(conversationId, user.uid, text);\n      setMessage("");\n      setPicker(false);\n      inputRef.current?.focus();\n    } catch (err) {\n      notify(mapFirestoreError(err));\n    }\n  };'''
if old not in s: raise SystemExit('send block not found')
s = s.replace(old, new)
p.write_text(s)

p = Path('src/app/connections/page.tsx')
s = p.read_text()
old = '''      await findOrCreateDirectConversation(currentUser.uid, person.uid);\n      localStorage.setItem("nitra-open-chat", JSON.stringify({ id: person.uid, name: person.name, initials: person.initials, email: person.email, nitraId: person.nitraId, bio: person.bio || "", status: person.status || "Available", online: true }));'''
new = '''      const conversationId = await findOrCreateDirectConversation(currentUser.uid, person.uid);\n      localStorage.setItem("nitra-open-chat", JSON.stringify({ id: person.uid, name: person.name, initials: person.initials, email: person.email, nitraId: person.nitraId, bio: person.bio || "", status: person.status || "Available", online: true, conversationId }));'''
if old not in s: raise SystemExit('messageFriend block not found')
s = s.replace(old, new)
p.write_text(s)
